baseURL = "https://thisismitime.com/"
languageCode = "en-us"
title = "this is mitime"
publishDir = "docs" 
enableGitInfo = true
footnoteReturnLinkContents = "↩"
lastmod = [":fileModTime", ":default"] # auto populates lastmod date

[params]
  _merge = "deep"
  analyticsid = ""
  bodyid = "thisismitime" # allows sites to override base theme body style
  additionalmetatags = "<meta name=\"msvalidate.01\" content=\"\" />" 
  contactformEndpoint = "https://app.99inbound.com/api/e/1a-dfbvP" 
  contactformAntispam = "<div style=\"position: absolute; left: -5000px;\"> <input type=\"checkbox\" name=\"grandmas_red_glossy_housecat\" value=\"1\" tabindex=\"-1\" autocomplete=\"no\"> </div>"
# see https://blog.fullstackdigital.com/how-to-use-hugo-template-variables-in-scss-files-in-2018-b8a834accce
# https://discourse.gohugo.io/t/how-to-override-css-classes-with-hugo/3033/2
# color scheme for base theme

# theming and reusable code
[module]
  _merge = "deep"
  [[module.imports]]
    path = "github.com/ajsmith607/undergo"
  [[module.imports]]
    path = "github.com/ajsmith607/mitimer"
 
[markup]
  _merge = "deep"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
